[workspace]
authors = ["Per Unneberg <per.unneberg@scilifelab.se>"]
channels = ["conda-forge"]
name = "nbis-quarto-revealjs"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pre-commit = ">=4.2.0,<5"
